server:
  port: 8084
spring:
  application:
    name: USER-PROFILE-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/skillhub_profiles

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

logging:
  level:
    com.skillhub.profile: DEBUG
    org.springframework.data.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"